name: dev_bardic
services:
  app:
    image: ghcr.io/gitvex/bardicinspiration_dev:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    # ports:
    #   - "8080:3000"
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dev_bardicinspiration.rule=Host(`dev.bardicinspiration.cc`)'
      - 'traefik.http.services.dev_bardicinspiration.loadbalancer.server.port=3000'
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true